### ISSUE TITLE
handle www.spatialreference.org (missing A Record in domain)

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/spatialreference.org#19] opened 2024-03-18 11:56 UTC
- goal is to handle the case for when a user goes to: https://www.spatialreference.org/
- possibly through a missing A Record entry in the DNS settings for the domain

**Comment by jjimenezshaw** [comment] 2024-03-18 13:32
Testing it Firefox, it works perfectly, with a 301 redirect to https://spatialreference.org/
in Chrome it says `NET::ERR_CERT_COMMON_NAME_INVALID`
Is that a problem for GitHub or for us?

**Comment by hobu** [comment] 2024-03-18 13:35
yeah the issue is the 301 works for the DNS but the SSL cert being served to us is GitHub's.  We would need to self-host a server with an SSL cert at www and then 301 it to the apex domain.

Do we need to support www? are there that many links out there? Is it worth the trouble?

**Comment by jjimenezshaw** [comment] 2024-05-09 18:48
@jmckenna due to the complexity and cost of the solution, I would just close this issue.

**Closed** 2024-05-09 19:24 UTC
